### ISSUE TITLE
Task: Add colors to cell

### ISSUE THREAD

**Issue by tirth132** [tirth132/dino-engine#3]
Task: Implement `CellColor` class which provides colors to cells

## Description
Cells need to have different colors. Class `CellColor` provides colors using RGB color system. It provides basic colors inbuild. It also prevents invalid values.

## Task requires
- [x] A class called `CellColor` must be found under `com.dino.cell` package.
- [x] Cell color class should have three final ints to store red, green and blue values.
- [x] The constructor should check for validity and throw exception for invalid values.
- [x] It should have getters for red, green and blue values.
- [x] The class should override `toString()` method of Object class.
- [x] Class should have inbuild red, gree, blue, yellow. orange, black. gray and white colors.

Issue can be closed after passing test case testing for requirement.

**Comment by tirth132** [comment]
Class `CellColor` compromises with last task of in-build colors but that can be ignored for now. So the issue is closed with this issue.
