### ISSUE TITLE
Task: Images on cells

### ISSUE THREAD

**Issue by tirth132** [tirth132/dino-engine#4]
Task: Make class `CellImage` so cells can have images too.

## Description
Some games need complex images on cells. You can use `CellImage` class to have an image on cell. You just need to provide path to image for using cell images. This class also provides methods to rotate, resize  and crop images.

## Task requires
- [ ] A class called `CellImage` must be found inside `com.dino.cell` package.
- [ ] The constructor should create `Image` object with given path.
- [ ] The class should throw `FileNotFoundException` if file could not be found.
- [ ] The class should have getter which returns `Image` object.
- [ ] The class should have `getImageFile()` method which return image as `File` object.
- [ ] The class should have `rotate()` method which rotates image.
- [ ] The class should have `resize()` method by which image can be resized.
- [ ] The class should have `crop()` method by which image can be croped.

Issue can be closed after passing test case testing for requirement.
