### ISSUE TITLE
Epic: Game board implementation 

### ISSUE THREAD

**Issue by tirth132** [tirth132/dino-engine#6]
Epic: Implementation of `Board` class to manage game board

## Description
Make a class which can be used to handle board which is a 2D array of cells. This class also provides tools for avoiding to write silly algorithms for every action to take on board.

## Task List
- [x] Task 1: [Make primary `Cell` class](https://github.com/tirth132/game-engine/issues/2)
- [x] Task 2: [Make cells be able to have colors.](https://github.com/tirth132/game-engine/issues/3)
- [ ] Task 3: [Make cells to be able to have images on them.](https://github.com/tirth132/game-engine/issues/4)
